### ISSUE TITLE
It seems that it can't be generated under windows.

### ISSUE THREAD

**Issue by fusss9** [thewhiteh4t/flashsploit#1]
It seems that it can't be generated under windows.

**Comment by thewhiteh4t** [comment]
yes @mrguai flashploit is designed to work on OS like Kali Linux and Blackarch, as they have all the tools required by flashsploit pre-installed, this reduces the need of a install script and saves time of users, so please convince me...why should I add support for windows?

**Comment by fusss9** [comment]
There are quite a lot of people using Windows.

**Comment by thewhiteh4t** [comment]
@mrguai if you want to use it on something like commando vm or kali linux wsl then I can add support, otherwise it's stupid

**Comment by mrguai** [comment]
OK, thanks

**Comment by mrguai** [comment]
@thewhiteh4t OK, thanks

**Comment by Vel1khan** [comment]
I agree with @thewhiteh4t on this one, why don't you close this issue already @mrguai if you can simply install the pre-requisites on windows yourself or fork the project and create your own install script?
